### ISSUE TITLE
Error while preparing the enviroment

### ISSUE THREAD

**Issue by krsudhar** [jpmorganchase/quorum-cloud#11]
Hi,

I have installed aws in my ubuntu machine and configured with the key and secret key. When I am running the code for preparation of aws environment 
`aws cloudformation create-stack --stack-name quorum-prepare-environment --template-body file://./quorum-prepare-environment.cfn.yml`

I am getting below error.
`Error parsing parameter '--template-body': Unable to load paramfile file://./quo                                                                                        rum-prepare-environment.cfn.yml: [Errno 2] No such file or directory: './quorum-                                                                                        prepare-environment.cfn.yml'`

Can someone let me know what am I missing

**Comment by trung** [comment]
@krsudhar the CF file is in `prepareEnvironment` folder. Your working directory need to be in that folder for the above command to work. Alternatively, you need to provide the right path to the file

**Comment by fixanoid** [comment]
Please reopen if there are additional questions.
