### ISSUE TITLE
Failed to run quorum and tessera nodes

### ISSUE THREAD

**Issue by wgn1993** [jpmorganchase/quorum-cloud#16]
after the deployment, the bastion node is created on EC2 dashboard, when I execute “Node1“ after I connect to bastion node using ssh, it reports "Command not found" and here are the cloudwatch logs under /ecs/quorum/dev:
**/quorum-run:**
Wait until metadata bootstrap completed ...
**/tessera-run:**
Wait until metadata bootstrap completed ...
**/metadata-bootstrap:**
Timestamp | Message
  | 2021-10-19T06:25:22.674+08:00 | Wait until Node Key is ready ...
  | 2021-10-19T06:25:25.683+08:00 | fetch http://dl-cdn.alpinelinux.org/alpine/v3.10/main/x86_64/APKINDEX.tar.gz
  | 2021-10-19T06:25:25.846+08:00 | fetch http://dl-cdn.alpinelinux.org/alpine/v3.10/community/x86_64/APKINDEX.tar.gz
  | 2021-10-19T06:25:26.002+08:00 | v3.10.9-43-g3feb769ea3 [http://dl-cdn.alpinelinux.org/alpine/v3.10/main]
  | 2021-10-19T06:25:26.002+08:00 | v3.10.6-10-ged79a86de3 [http://dl-cdn.alpinelinux.org/alpine/v3.10/community]
  | 2021-10-19T06:25:26.002+08:00 | OK: 10370 distinct packages available
  | 2021-10-19T06:25:26.140+08:00 | (1/2) Installing oniguruma (6.9.4-r1)
  | 2021-10-19T06:25:26.176+08:00 | (2/2) Installing jq (1.6-r0)
  | 2021-10-19T06:25:26.194+08:00 | Executing busybox-1.30.1-r2.trigger
  | 2021-10-19T06:25:26.202+08:00 | OK: 114 MiB in 51 packages
  | 2021-10-19T06:25:26.269+08:00 | Task Revision: 2
  | 2021-10-19T06:25:26.314+08:00 | Host IP: 10.115.11.203
  | 2021-10-19T06:25:27.941+08:00 | Completed 129 Bytes/129 Bytes (557 Bytes/s) with 1 file(s) remaining upload: qdata/node_id to s3://us-west-2-ecs-dev-da1c2563a2ff5d3f/rev_2/nodeids/ip_10_115_11_203
  | 2021-10-19T06:25:28.712+08:00 | Completed 14 Bytes/14 Bytes (111 Bytes/s) with 1 file(s) remaining upload: qdata/host_ip to s3://us-west-2-ecs-dev-da1c2563a2ff5d3f/rev_2/hosts/ip_10_115_11_203
  | 2021-10-19T06:25:29.503+08:00 | Completed 41 Bytes/41 Bytes (294 Bytes/s) with 1 file(s) remaining upload: qdata/first_account_address to s3://us-west-2-ecs-dev-da1c2563a2ff5d3f/rev_2/accounts/ip_10_115_11_203
  | 2021-10-19T06:25:29.573+08:00 | Wait for other containers to report their IPs ... 0/7
  | 2021-10-19T06:25:31.720+08:00 | Wait for other containers to report their IPs ... 26/7
  | 2021-10-19T06:25:33.893+08:00 | All containers have reported their IPs
  | 2021-10-19T06:25:33.895+08:00 | Wait for other nodes to report their accounts ... 0/7
  | 2021-10-19T06:25:36.047+08:00 | Wait for other nodes to report their accounts ... 26/7
  | 2021-10-19T06:25:38.212+08:00 | All nodes have registered accounts
  | 2021-10-19T06:25:38.213+08:00 | Wait for other nodes to report their IDs ... 0/7
  | 2021-10-19T06:25:40.326+08:00 | Wait for other nodes to report their IDs ... 26/7
  | 2021-10-19T06:25:42.459+08:00 | All nodes have registered their IDs
  | 2021-10-19T06:25:42.475+08:00 | % Total % Received % Xferd Average Speed Time Time Time Current
  | 2021-10-19T06:25:42.475+08:00 | Dload Upload Total Spent Left Speed
  | 2021-10-19T06:25:42.496+08:00 | 0 0 0 0 0 0 0 0 --:--:-- --:--:-- --:--:-- 0 100 10 100 10 0 0 476 0 --:--:-- --:--:-- --:--:-- 476
  | 2021-10-19T06:25:42.498+08:00 | tar: invalid magic
  | 2021-10-19T06:25:42.499+08:00 | tar: short read

it seems the quorum and tessera node is not running due to failure of metadata bootstrap setup, how could I fix this issue?
Thanks!

**Comment by trung** [comment]
It seems the failure is in here: https://github.com/ConsenSys/quorum-cloud/blob/323d00d598121667319120192f91d0d20cc6fb1c/aws/templates/container_definition_bootstrap.tf#L90-L91

Bintray was sunset, artifacts are now in [Cloudsmith](https://cloudsmith.io/~consensys/repos/quorum-tools/packages/)

Can you change the curl URL to: `https://artifacts.consensys.net/public/quorum-tools/raw/versions/v1.1.0/istanbul-tools_v1.1.0_linux_amd64.tar.gz` and give a try?

**Comment by wgn1993** [comment]
hi , I clean up all the resources using terraform destroy, and change the curl URL in container_definition_bootstrap.tf, redeploy the network using terraform apply, but it give a new error:
  | 2021-10-21T15:56:34.025+08:00 | All nodes have registered their IDs
-- | -- | --
  | 2021-10-21T15:56:34.055+08:00 | % Total % Received % Xferd Average Speed Time Time Time Current
  | 2021-10-21T15:56:34.055+08:00 | Dload Upload Total Spent Left Speed
  | 2021-10-21T15:56:34.486+08:00 | 0 0 0 0 0 0 0 0 --:--:-- --:--:-- --:--:-- 0 100 21.2M 100 21.2M 0 0 49.3M 0 --:--:-- --:--:-- --:--:-- 49.3M
  | 2021-10-21T15:56:34.489+08:00 | istanbul
  | 2021-10-21T15:56:35.076+08:00 | qbft
  | 2021-10-21T15:56:35.078+08:00 | /bin/sh: ./istanbul: not found

in my terraform.auto.tfvars, the default config is:
consensus_mechanism = "istanbul"
tx_privacy_engine = "tessera"

Is there anything wrong for this config? thanks for helping

**Comment by wgn1993** [comment]
and I try to modify the terraform.auto.tfvars, after that I execute "terraform init -backend-config=terraform.auto.backend_config -reconfigure
terraform apply" but don't see any new logs from CloudWatch group, do I need to start from the beginning to redeploy the whole network?

**Comment by trung** [comment]
> hi , I clean up all the resources using terraform destroy, and change the curl URL in container_definition_bootstrap.tf, redeploy the network using terraform apply, but it give a new error

Can you try with `v1.0.2` URL instead? i.e.: `https://artifacts.consensys.net/public/quorum-tools/raw/versions/v1.0.2/istanbul-tools_v1.0.2_linux_amd64.tar.gz`

I suggest to start with the clean state by doing `terraform destroy` and cleaning up all the created resources.

**Comment by wgn1993** [comment]
> > hi , I clean up all the resources using terraform destroy, and change the curl URL in container_definition_bootstrap.tf, redeploy the network using terraform apply, but it give a new error
> 
> Can you try with `v1.0.2` URL instead? i.e.: `https://artifacts.consensys.net/public/quorum-tools/raw/versions/v1.0.2/istanbul-tools_v1.0.2_linux_amd64.tar.gz`
> 
> I suggest to start with the clean state by doing `terraform destroy` and cleaning up all the created resources.

hi, I updated the v1.0.2 URL and did 'terraform destroy' and 'terraform apply' , found that every time I try there will be some nodes in ECS are in pending state, ...each task looks like this:
<img width="709" alt="Capture" src="https://user-images.githubusercontent.com/15976364/138715590-33614fe6-9976-453d-aebf-2a8b42814e28.PNG"> 
it takes much longer time than before to get all  nodes running, finally the metadata setup seems to be successful, but tessera is not ready to run:
**/metadata-bootstrap**
...
Wait until privacy engine initialized ...
**/tessera-run**
2021-10-27T16:30:11.978+08:00 | Wait until metadata bootstrap completed ...
  | 2021-10-27T16:30:32.999+08:00 | fetch https://dl-cdn.alpinelinux.org/alpine/v3.14/main/x86_64/APKINDEX.tar.gz
  | 2021-10-27T16:30:33.117+08:00 | fetch https://dl-cdn.alpinelinux.org/alpine/v3.14/community/x86_64/APKINDEX.tar.gz
  | 2021-10-27T16:30:33.345+08:00 | v3.14.2-116-gea9b052f30 [https://dl-cdn.alpinelinux.org/alpine/v3.14/main]
  | 2021-10-27T16:30:33.345+08:00 | v3.14.2-112-g40db7c160b [https://dl-cdn.alpinelinux.org/alpine/v3.14/community]
  | 2021-10-27T16:30:33.345+08:00 | OK: 14945 distinct packages available
  | 2021-10-27T16:30:33.593+08:00 | (1/2) Installing oniguruma (6.9.7.1-r0)
  | 2021-10-27T16:30:33.659+08:00 | (2/2) Installing jq (1.6-r1)
  | 2021-10-27T16:30:33.675+08:00 | Executing busybox-1.33.1-r3.trigger
  | 2021-10-27T16:30:33.679+08:00 | Executing glibc-bin-2.33-r0.trigger
  | 2021-10-27T16:30:33.682+08:00 | /usr/glibc-compat/sbin/ldconfig: /usr/glibc-compat/lib/ld-linux-x86-64.so.2 is not a symbolic link
  | 2021-10-27T16:30:33.689+08:00 | OK: 18 MiB in 19 packages
  | 2021-10-27T16:30:33.725+08:00 | Error: Unable to access jarfile /tessera/tessera-app.jar

**Comment by wgn1993** [comment]
BTW, I noticed that in README it was mentioned that the quorum cloud is for testing purpose but not for production usage, is there any recommended quorum containerization solution we can use for deployment or you guys has ever used before, thanks!
